### ISSUE TITLE
x5092json module is empty

### ISSUE THREAD

**Issue by athoune** [jcrowgey/x5092json#4]
```
>>> import x5092json
>>> dir(x5092json)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
```

The example in the README is broken.

**Comment by jcrowgey** [comment]
You're absolutely right, thank you.

The `x5092json` package provides the `x509parser` module, alongside some utilities and patching modules.  So, the example should be:

```
>>> from x5092json import x509parser
```

Then, the `load_certificate` function is actually in `x509parser`.  I'll update the documentation.

**Comment by jcrowgey** [comment]
Relatedly, debugging your issue reveals some other bug in loading certificates.  I've added a failing test and I'll update the package shortly with a fix.
